# Generated by Django 3.0.6 on 2020-12-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='label',
        ),
        migrations.AddField(
            model_name='note',
            name='label',
            field=models.ManyToManyField(blank=True, related_name='labled_notes', to='notes.Label'),
        ),
    ]
